// <auto-generated />
namespace BGH_Kompakt.Migrartions.ActivityRequests
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Assurance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Assurance));
        
        string IMigrationMetadata.Id
        {
            get { return "202507041314112_Assurance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
