// <auto-generated />
namespace BGH_Kompakt.Migrartions.ActivityRequests
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class _3_014_0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3_014_0));
        
        string IMigrationMetadata.Id
        {
            get { return "202509091651228_3_014_0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
