// <auto-generated />
namespace BGH_Kompakt.Migrartions.Users
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class _3_017_2_Besoldung : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3_017_2_Besoldung));
        
        string IMigrationMetadata.Id
        {
            get { return "202509301534578_3_017_2_Besoldung"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
