// <auto-generated />
namespace BGH_Kompakt.Migrartions.Users
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class _3_016_Straf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3_016_Straf));
        
        string IMigrationMetadata.Id
        {
            get { return "202509180626522_3_016_Straf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
