// <auto-generated />
namespace BGH_Kompakt.Migrartions.Users
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Update3_013 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update3_013));
        
        string IMigrationMetadata.Id
        {
            get { return "202509050913148_Update3_013"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
