// <auto-generated />
namespace BGH_Kompakt.Migrartions.MP
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class MPEMailMPSetting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MPEMailMPSetting));
        
        string IMigrationMetadata.Id
        {
            get { return "202507090547129_MPEMailMPSetting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
